/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppApprovalsRouteImport } from './routes/_app/approvals'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AppBotsNewRouteImport } from './routes/_app/bots.new'
import { Route as AppSettingsSectionRouteImport } from './routes/_app/settings_.$section'
import { Route as AppBotsBotIdIndexRouteImport } from './routes/_app/bots.$botId.index'
import { Route as AppBotsBotIdComputerRouteImport } from './routes/_app/bots.$botId.computer'
import { Route as AppBotsBotIdEditRouteImport } from './routes/_app/bots.$botId.edit'
import { Route as AppBotsBotIdMemoryRouteImport } from './routes/_app/bots.$botId.memory'
import { Route as AppBotsBotIdRoutinesRouteImport } from './routes/_app/bots.$botId.routines'
import { Route as AppBotsBotIdUsageRouteImport } from './routes/_app/bots.$botId.usage'
import { Route as AppBotsBotIdThreadsThreadIdRouteImport } from './routes/_app/bots.$botId.threads.$threadId'
import { Route as AppBotsBotIdThreadsThreadIdToolResultsRunIdCallIdRouteImport } from './routes/_app/bots.$botId.threads.$threadId_.tool-results.$runId.$callId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AppBotsNewRoute = AppBotsNewRouteImport.update({
  id: '/bots/new',
  path: '/bots/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSectionRoute = AppSettingsSectionRouteImport.update({
  id: '/settings_/$section',
  path: '/settings/$section',
  getParentRoute: () => AppRoute,
} as any)
const AppBotsBotIdIndexRoute = AppBotsBotIdIndexRouteImport.update({
  id: '/bots/$botId/',
  path: '/bots/$botId/',
  getParentRoute: () => AppRoute,
} as any)
const AppBotsBotIdComputerRoute = AppBotsBotIdComputerRouteImport.update({
  id: '/bots/$botId/computer',
  path: '/bots/$botId/computer',
  getParentRoute: () => AppRoute,
} as any)
const AppBotsBotIdEditRoute = AppBotsBotIdEditRouteImport.update({
  id: '/bots/$botId/edit',
  path: '/bots/$botId/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppBotsBotIdMemoryRoute = AppBotsBotIdMemoryRouteImport.update({
  id: '/bots/$botId/memory',
  path: '/bots/$botId/memory',
  getParentRoute: () => AppRoute,
} as any)
const AppBotsBotIdRoutinesRoute = AppBotsBotIdRoutinesRouteImport.update({
  id: '/bots/$botId/routines',
  path: '/bots/$botId/routines',
  getParentRoute: () => AppRoute,
} as any)
const AppBotsBotIdUsageRoute = AppBotsBotIdUsageRouteImport.update({
  id: '/bots/$botId/usage',
  path: '/bots/$botId/usage',
  getParentRoute: () => AppRoute,
} as any)
const AppBotsBotIdThreadsThreadIdRoute =
  AppBotsBotIdThreadsThreadIdRouteImport.update({
    id: '/bots/$botId/threads/$threadId',
    path: '/bots/$botId/threads/$threadId',
    getParentRoute: () => AppRoute,
  } as any)
const AppBotsBotIdThreadsThreadIdToolResultsRunIdCallIdRoute =
  AppBotsBotIdThreadsThreadIdToolResultsRunIdCallIdRouteImport.update({
    id: '/bots/$botId/threads/$threadId_/tool-results/$runId/$callId',
    path: '/bots/$botId/threads/$threadId/tool-results/$runId/$callId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/approvals': typeof AppApprovalsRoute
  '/settings': typeof AppSettingsRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/bots/new': typeof AppBotsNewRoute
  '/settings/$section': typeof AppSettingsSectionRoute
  '/bots/$botId/computer': typeof AppBotsBotIdComputerRoute
  '/bots/$botId/edit': typeof AppBotsBotIdEditRoute
  '/bots/$botId/memory': typeof AppBotsBotIdMemoryRoute
  '/bots/$botId/routines': typeof AppBotsBotIdRoutinesRoute
  '/bots/$botId/usage': typeof AppBotsBotIdUsageRoute
  '/bots/$botId/': typeof AppBotsBotIdIndexRoute
  '/bots/$botId/threads/$threadId': typeof AppBotsBotIdThreadsThreadIdRoute
  '/bots/$botId/threads/$threadId/tool-results/$runId/$callId': typeof AppBotsBotIdThreadsThreadIdToolResultsRunIdCallIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/approvals': typeof AppApprovalsRoute
  '/settings': typeof AppSettingsRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/bots/new': typeof AppBotsNewRoute
  '/settings/$section': typeof AppSettingsSectionRoute
  '/bots/$botId/computer': typeof AppBotsBotIdComputerRoute
  '/bots/$botId/edit': typeof AppBotsBotIdEditRoute
  '/bots/$botId/memory': typeof AppBotsBotIdMemoryRoute
  '/bots/$botId/routines': typeof AppBotsBotIdRoutinesRoute
  '/bots/$botId/usage': typeof AppBotsBotIdUsageRoute
  '/bots/$botId': typeof AppBotsBotIdIndexRoute
  '/bots/$botId/threads/$threadId': typeof AppBotsBotIdThreadsThreadIdRoute
  '/bots/$botId/threads/$threadId/tool-results/$runId/$callId': typeof AppBotsBotIdThreadsThreadIdToolResultsRunIdCallIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_app/': typeof AppIndexRoute
  '/_app/bots/new': typeof AppBotsNewRoute
  '/_app/settings_/$section': typeof AppSettingsSectionRoute
  '/_app/bots/$botId/computer': typeof AppBotsBotIdComputerRoute
  '/_app/bots/$botId/edit': typeof AppBotsBotIdEditRoute
  '/_app/bots/$botId/memory': typeof AppBotsBotIdMemoryRoute
  '/_app/bots/$botId/routines': typeof AppBotsBotIdRoutinesRoute
  '/_app/bots/$botId/usage': typeof AppBotsBotIdUsageRoute
  '/_app/bots/$botId/': typeof AppBotsBotIdIndexRoute
  '/_app/bots/$botId/threads/$threadId': typeof AppBotsBotIdThreadsThreadIdRoute
  '/_app/bots/$botId/threads/$threadId_/tool-results/$runId/$callId': typeof AppBotsBotIdThreadsThreadIdToolResultsRunIdCallIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/bots/new'
    | '/settings/$section'
    | '/bots/$botId/computer'
    | '/bots/$botId/edit'
    | '/bots/$botId/memory'
    | '/bots/$botId/routines'
    | '/bots/$botId/usage'
    | '/bots/$botId/'
    | '/bots/$botId/threads/$threadId'
    | '/bots/$botId/threads/$threadId/tool-results/$runId/$callId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/bots/new'
    | '/settings/$section'
    | '/bots/$botId/computer'
    | '/bots/$botId/edit'
    | '/bots/$botId/memory'
    | '/bots/$botId/routines'
    | '/bots/$botId/usage'
    | '/bots/$botId'
    | '/bots/$botId/threads/$threadId'
    | '/bots/$botId/threads/$threadId/tool-results/$runId/$callId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/approvals'
    | '/_app/settings'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_app/'
    | '/_app/bots/new'
    | '/_app/settings_/$section'
    | '/_app/bots/$botId/computer'
    | '/_app/bots/$botId/edit'
    | '/_app/bots/$botId/memory'
    | '/_app/bots/$botId/routines'
    | '/_app/bots/$botId/usage'
    | '/_app/bots/$botId/'
    | '/_app/bots/$botId/threads/$threadId'
    | '/_app/bots/$botId/threads/$threadId_/tool-results/$runId/$callId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/bots/new': {
      id: '/_app/bots/new'
      path: '/bots/new'
      fullPath: '/bots/new'
      preLoaderRoute: typeof AppBotsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings_/$section': {
      id: '/_app/settings_/$section'
      path: '/settings/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof AppSettingsSectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bots/$botId/': {
      id: '/_app/bots/$botId/'
      path: '/bots/$botId'
      fullPath: '/bots/$botId/'
      preLoaderRoute: typeof AppBotsBotIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bots/$botId/computer': {
      id: '/_app/bots/$botId/computer'
      path: '/bots/$botId/computer'
      fullPath: '/bots/$botId/computer'
      preLoaderRoute: typeof AppBotsBotIdComputerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bots/$botId/edit': {
      id: '/_app/bots/$botId/edit'
      path: '/bots/$botId/edit'
      fullPath: '/bots/$botId/edit'
      preLoaderRoute: typeof AppBotsBotIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bots/$botId/memory': {
      id: '/_app/bots/$botId/memory'
      path: '/bots/$botId/memory'
      fullPath: '/bots/$botId/memory'
      preLoaderRoute: typeof AppBotsBotIdMemoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bots/$botId/routines': {
      id: '/_app/bots/$botId/routines'
      path: '/bots/$botId/routines'
      fullPath: '/bots/$botId/routines'
      preLoaderRoute: typeof AppBotsBotIdRoutinesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bots/$botId/usage': {
      id: '/_app/bots/$botId/usage'
      path: '/bots/$botId/usage'
      fullPath: '/bots/$botId/usage'
      preLoaderRoute: typeof AppBotsBotIdUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bots/$botId/threads/$threadId': {
      id: '/_app/bots/$botId/threads/$threadId'
      path: '/bots/$botId/threads/$threadId'
      fullPath: '/bots/$botId/threads/$threadId'
      preLoaderRoute: typeof AppBotsBotIdThreadsThreadIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bots/$botId/threads/$threadId_/tool-results/$runId/$callId': {
      id: '/_app/bots/$botId/threads/$threadId_/tool-results/$runId/$callId'
      path: '/bots/$botId/threads/$threadId/tool-results/$runId/$callId'
      fullPath: '/bots/$botId/threads/$threadId/tool-results/$runId/$callId'
      preLoaderRoute: typeof AppBotsBotIdThreadsThreadIdToolResultsRunIdCallIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBotsNewRoute: typeof AppBotsNewRoute
  AppSettingsSectionRoute: typeof AppSettingsSectionRoute
  AppBotsBotIdComputerRoute: typeof AppBotsBotIdComputerRoute
  AppBotsBotIdEditRoute: typeof AppBotsBotIdEditRoute
  AppBotsBotIdMemoryRoute: typeof AppBotsBotIdMemoryRoute
  AppBotsBotIdRoutinesRoute: typeof AppBotsBotIdRoutinesRoute
  AppBotsBotIdUsageRoute: typeof AppBotsBotIdUsageRoute
  AppBotsBotIdIndexRoute: typeof AppBotsBotIdIndexRoute
  AppBotsBotIdThreadsThreadIdRoute: typeof AppBotsBotIdThreadsThreadIdRoute
  AppBotsBotIdThreadsThreadIdToolResultsRunIdCallIdRoute: typeof AppBotsBotIdThreadsThreadIdToolResultsRunIdCallIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApprovalsRoute: AppApprovalsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppBotsNewRoute: AppBotsNewRoute,
  AppSettingsSectionRoute: AppSettingsSectionRoute,
  AppBotsBotIdComputerRoute: AppBotsBotIdComputerRoute,
  AppBotsBotIdEditRoute: AppBotsBotIdEditRoute,
  AppBotsBotIdMemoryRoute: AppBotsBotIdMemoryRoute,
  AppBotsBotIdRoutinesRoute: AppBotsBotIdRoutinesRoute,
  AppBotsBotIdUsageRoute: AppBotsBotIdUsageRoute,
  AppBotsBotIdIndexRoute: AppBotsBotIdIndexRoute,
  AppBotsBotIdThreadsThreadIdRoute: AppBotsBotIdThreadsThreadIdRoute,
  AppBotsBotIdThreadsThreadIdToolResultsRunIdCallIdRoute:
    AppBotsBotIdThreadsThreadIdToolResultsRunIdCallIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
