/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AppThreadsThreadIdRouteImport } from './routes/_app/threads.$threadId'
import { Route as AppBotsBotIdMemoryRouteImport } from './routes/_app/bots.$botId.memory'
import { Route as AppThreadsThreadIdToolResultsRunIdCallIdRouteImport } from './routes/_app/threads.$threadId_.tool-results.$runId.$callId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AppThreadsThreadIdRoute = AppThreadsThreadIdRouteImport.update({
  id: '/threads/$threadId',
  path: '/threads/$threadId',
  getParentRoute: () => AppRoute,
} as any)
const AppBotsBotIdMemoryRoute = AppBotsBotIdMemoryRouteImport.update({
  id: '/bots/$botId/memory',
  path: '/bots/$botId/memory',
  getParentRoute: () => AppRoute,
} as any)
const AppThreadsThreadIdToolResultsRunIdCallIdRoute =
  AppThreadsThreadIdToolResultsRunIdCallIdRouteImport.update({
    id: '/threads/$threadId_/tool-results/$runId/$callId',
    path: '/threads/$threadId/tool-results/$runId/$callId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/threads/$threadId': typeof AppThreadsThreadIdRoute
  '/bots/$botId/memory': typeof AppBotsBotIdMemoryRoute
  '/threads/$threadId/tool-results/$runId/$callId': typeof AppThreadsThreadIdToolResultsRunIdCallIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/threads/$threadId': typeof AppThreadsThreadIdRoute
  '/bots/$botId/memory': typeof AppBotsBotIdMemoryRoute
  '/threads/$threadId/tool-results/$runId/$callId': typeof AppThreadsThreadIdToolResultsRunIdCallIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_app/': typeof AppIndexRoute
  '/_app/threads/$threadId': typeof AppThreadsThreadIdRoute
  '/_app/bots/$botId/memory': typeof AppBotsBotIdMemoryRoute
  '/_app/threads/$threadId_/tool-results/$runId/$callId': typeof AppThreadsThreadIdToolResultsRunIdCallIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/threads/$threadId'
    | '/bots/$botId/memory'
    | '/threads/$threadId/tool-results/$runId/$callId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/threads/$threadId'
    | '/bots/$botId/memory'
    | '/threads/$threadId/tool-results/$runId/$callId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_app/'
    | '/_app/threads/$threadId'
    | '/_app/bots/$botId/memory'
    | '/_app/threads/$threadId_/tool-results/$runId/$callId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/threads/$threadId': {
      id: '/_app/threads/$threadId'
      path: '/threads/$threadId'
      fullPath: '/threads/$threadId'
      preLoaderRoute: typeof AppThreadsThreadIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bots/$botId/memory': {
      id: '/_app/bots/$botId/memory'
      path: '/bots/$botId/memory'
      fullPath: '/bots/$botId/memory'
      preLoaderRoute: typeof AppBotsBotIdMemoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/threads/$threadId_/tool-results/$runId/$callId': {
      id: '/_app/threads/$threadId_/tool-results/$runId/$callId'
      path: '/threads/$threadId/tool-results/$runId/$callId'
      fullPath: '/threads/$threadId/tool-results/$runId/$callId'
      preLoaderRoute: typeof AppThreadsThreadIdToolResultsRunIdCallIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppThreadsThreadIdRoute: typeof AppThreadsThreadIdRoute
  AppBotsBotIdMemoryRoute: typeof AppBotsBotIdMemoryRoute
  AppThreadsThreadIdToolResultsRunIdCallIdRoute: typeof AppThreadsThreadIdToolResultsRunIdCallIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppThreadsThreadIdRoute: AppThreadsThreadIdRoute,
  AppBotsBotIdMemoryRoute: AppBotsBotIdMemoryRoute,
  AppThreadsThreadIdToolResultsRunIdCallIdRoute:
    AppThreadsThreadIdToolResultsRunIdCallIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
