/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppApprovalsRouteImport } from './routes/_app/approvals'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AppBotsNewRouteImport } from './routes/_app/bots.new'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings.index'
import { Route as AppSettingsAccountRouteImport } from './routes/_app/settings.account'
import { Route as AppSettingsConnectionsRouteImport } from './routes/_app/settings.connections'
import { Route as AppSettingsMcpRouteImport } from './routes/_app/settings.mcp'
import { Route as AppSettingsNotificationsRouteImport } from './routes/_app/settings.notifications'
import { Route as AppSettingsSecretsRouteImport } from './routes/_app/settings.secrets'
import { Route as AppSettingsUsageRouteImport } from './routes/_app/settings.usage'
import { Route as AppThreadsThreadIdRouteImport } from './routes/_app/threads.$threadId'
import { Route as AppBotsBotIdComputerRouteImport } from './routes/_app/bots.$botId.computer'
import { Route as AppBotsBotIdEditRouteImport } from './routes/_app/bots.$botId.edit'
import { Route as AppBotsBotIdMemoryRouteImport } from './routes/_app/bots.$botId.memory'
import { Route as AppBotsBotIdUsageRouteImport } from './routes/_app/bots.$botId.usage'
import { Route as AppThreadsThreadIdToolResultsRunIdCallIdRouteImport } from './routes/_app/threads.$threadId_.tool-results.$runId.$callId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AppBotsNewRoute = AppBotsNewRouteImport.update({
  id: '/bots/new',
  path: '/bots/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsConnectionsRoute = AppSettingsConnectionsRouteImport.update({
  id: '/settings/connections',
  path: '/settings/connections',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsMcpRoute = AppSettingsMcpRouteImport.update({
  id: '/settings/mcp',
  path: '/settings/mcp',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsSecretsRoute = AppSettingsSecretsRouteImport.update({
  id: '/settings/secrets',
  path: '/settings/secrets',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsUsageRoute = AppSettingsUsageRouteImport.update({
  id: '/settings/usage',
  path: '/settings/usage',
  getParentRoute: () => AppRoute,
} as any)
const AppThreadsThreadIdRoute = AppThreadsThreadIdRouteImport.update({
  id: '/threads/$threadId',
  path: '/threads/$threadId',
  getParentRoute: () => AppRoute,
} as any)
const AppBotsBotIdComputerRoute = AppBotsBotIdComputerRouteImport.update({
  id: '/bots/$botId/computer',
  path: '/bots/$botId/computer',
  getParentRoute: () => AppRoute,
} as any)
const AppBotsBotIdEditRoute = AppBotsBotIdEditRouteImport.update({
  id: '/bots/$botId/edit',
  path: '/bots/$botId/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppBotsBotIdMemoryRoute = AppBotsBotIdMemoryRouteImport.update({
  id: '/bots/$botId/memory',
  path: '/bots/$botId/memory',
  getParentRoute: () => AppRoute,
} as any)
const AppBotsBotIdUsageRoute = AppBotsBotIdUsageRouteImport.update({
  id: '/bots/$botId/usage',
  path: '/bots/$botId/usage',
  getParentRoute: () => AppRoute,
} as any)
const AppThreadsThreadIdToolResultsRunIdCallIdRoute =
  AppThreadsThreadIdToolResultsRunIdCallIdRouteImport.update({
    id: '/threads/$threadId_/tool-results/$runId/$callId',
    path: '/threads/$threadId/tool-results/$runId/$callId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/approvals': typeof AppApprovalsRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/bots/new': typeof AppBotsNewRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/connections': typeof AppSettingsConnectionsRoute
  '/settings/mcp': typeof AppSettingsMcpRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/secrets': typeof AppSettingsSecretsRoute
  '/settings/usage': typeof AppSettingsUsageRoute
  '/threads/$threadId': typeof AppThreadsThreadIdRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/bots/$botId/computer': typeof AppBotsBotIdComputerRoute
  '/bots/$botId/edit': typeof AppBotsBotIdEditRoute
  '/bots/$botId/memory': typeof AppBotsBotIdMemoryRoute
  '/bots/$botId/usage': typeof AppBotsBotIdUsageRoute
  '/threads/$threadId/tool-results/$runId/$callId': typeof AppThreadsThreadIdToolResultsRunIdCallIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/approvals': typeof AppApprovalsRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/bots/new': typeof AppBotsNewRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/connections': typeof AppSettingsConnectionsRoute
  '/settings/mcp': typeof AppSettingsMcpRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/secrets': typeof AppSettingsSecretsRoute
  '/settings/usage': typeof AppSettingsUsageRoute
  '/threads/$threadId': typeof AppThreadsThreadIdRoute
  '/settings': typeof AppSettingsIndexRoute
  '/bots/$botId/computer': typeof AppBotsBotIdComputerRoute
  '/bots/$botId/edit': typeof AppBotsBotIdEditRoute
  '/bots/$botId/memory': typeof AppBotsBotIdMemoryRoute
  '/bots/$botId/usage': typeof AppBotsBotIdUsageRoute
  '/threads/$threadId/tool-results/$runId/$callId': typeof AppThreadsThreadIdToolResultsRunIdCallIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/approvals': typeof AppApprovalsRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_app/': typeof AppIndexRoute
  '/_app/bots/new': typeof AppBotsNewRoute
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/settings/connections': typeof AppSettingsConnectionsRoute
  '/_app/settings/mcp': typeof AppSettingsMcpRoute
  '/_app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/_app/settings/secrets': typeof AppSettingsSecretsRoute
  '/_app/settings/usage': typeof AppSettingsUsageRoute
  '/_app/threads/$threadId': typeof AppThreadsThreadIdRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/bots/$botId/computer': typeof AppBotsBotIdComputerRoute
  '/_app/bots/$botId/edit': typeof AppBotsBotIdEditRoute
  '/_app/bots/$botId/memory': typeof AppBotsBotIdMemoryRoute
  '/_app/bots/$botId/usage': typeof AppBotsBotIdUsageRoute
  '/_app/threads/$threadId_/tool-results/$runId/$callId': typeof AppThreadsThreadIdToolResultsRunIdCallIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/sign-in'
    | '/sign-up'
    | '/bots/new'
    | '/settings/account'
    | '/settings/connections'
    | '/settings/mcp'
    | '/settings/notifications'
    | '/settings/secrets'
    | '/settings/usage'
    | '/threads/$threadId'
    | '/settings/'
    | '/bots/$botId/computer'
    | '/bots/$botId/edit'
    | '/bots/$botId/memory'
    | '/bots/$botId/usage'
    | '/threads/$threadId/tool-results/$runId/$callId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/sign-in'
    | '/sign-up'
    | '/bots/new'
    | '/settings/account'
    | '/settings/connections'
    | '/settings/mcp'
    | '/settings/notifications'
    | '/settings/secrets'
    | '/settings/usage'
    | '/threads/$threadId'
    | '/settings'
    | '/bots/$botId/computer'
    | '/bots/$botId/edit'
    | '/bots/$botId/memory'
    | '/bots/$botId/usage'
    | '/threads/$threadId/tool-results/$runId/$callId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/approvals'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_app/'
    | '/_app/bots/new'
    | '/_app/settings/account'
    | '/_app/settings/connections'
    | '/_app/settings/mcp'
    | '/_app/settings/notifications'
    | '/_app/settings/secrets'
    | '/_app/settings/usage'
    | '/_app/threads/$threadId'
    | '/_app/settings/'
    | '/_app/bots/$botId/computer'
    | '/_app/bots/$botId/edit'
    | '/_app/bots/$botId/memory'
    | '/_app/bots/$botId/usage'
    | '/_app/threads/$threadId_/tool-results/$runId/$callId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/bots/new': {
      id: '/_app/bots/new'
      path: '/bots/new'
      fullPath: '/bots/new'
      preLoaderRoute: typeof AppBotsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/connections': {
      id: '/_app/settings/connections'
      path: '/settings/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof AppSettingsConnectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/mcp': {
      id: '/_app/settings/mcp'
      path: '/settings/mcp'
      fullPath: '/settings/mcp'
      preLoaderRoute: typeof AppSettingsMcpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/notifications': {
      id: '/_app/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/secrets': {
      id: '/_app/settings/secrets'
      path: '/settings/secrets'
      fullPath: '/settings/secrets'
      preLoaderRoute: typeof AppSettingsSecretsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/usage': {
      id: '/_app/settings/usage'
      path: '/settings/usage'
      fullPath: '/settings/usage'
      preLoaderRoute: typeof AppSettingsUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/threads/$threadId': {
      id: '/_app/threads/$threadId'
      path: '/threads/$threadId'
      fullPath: '/threads/$threadId'
      preLoaderRoute: typeof AppThreadsThreadIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bots/$botId/computer': {
      id: '/_app/bots/$botId/computer'
      path: '/bots/$botId/computer'
      fullPath: '/bots/$botId/computer'
      preLoaderRoute: typeof AppBotsBotIdComputerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bots/$botId/edit': {
      id: '/_app/bots/$botId/edit'
      path: '/bots/$botId/edit'
      fullPath: '/bots/$botId/edit'
      preLoaderRoute: typeof AppBotsBotIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bots/$botId/memory': {
      id: '/_app/bots/$botId/memory'
      path: '/bots/$botId/memory'
      fullPath: '/bots/$botId/memory'
      preLoaderRoute: typeof AppBotsBotIdMemoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bots/$botId/usage': {
      id: '/_app/bots/$botId/usage'
      path: '/bots/$botId/usage'
      fullPath: '/bots/$botId/usage'
      preLoaderRoute: typeof AppBotsBotIdUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/threads/$threadId_/tool-results/$runId/$callId': {
      id: '/_app/threads/$threadId_/tool-results/$runId/$callId'
      path: '/threads/$threadId/tool-results/$runId/$callId'
      fullPath: '/threads/$threadId/tool-results/$runId/$callId'
      preLoaderRoute: typeof AppThreadsThreadIdToolResultsRunIdCallIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBotsNewRoute: typeof AppBotsNewRoute
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsConnectionsRoute: typeof AppSettingsConnectionsRoute
  AppSettingsMcpRoute: typeof AppSettingsMcpRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsSecretsRoute: typeof AppSettingsSecretsRoute
  AppSettingsUsageRoute: typeof AppSettingsUsageRoute
  AppThreadsThreadIdRoute: typeof AppThreadsThreadIdRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppBotsBotIdComputerRoute: typeof AppBotsBotIdComputerRoute
  AppBotsBotIdEditRoute: typeof AppBotsBotIdEditRoute
  AppBotsBotIdMemoryRoute: typeof AppBotsBotIdMemoryRoute
  AppBotsBotIdUsageRoute: typeof AppBotsBotIdUsageRoute
  AppThreadsThreadIdToolResultsRunIdCallIdRoute: typeof AppThreadsThreadIdToolResultsRunIdCallIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApprovalsRoute: AppApprovalsRoute,
  AppIndexRoute: AppIndexRoute,
  AppBotsNewRoute: AppBotsNewRoute,
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsConnectionsRoute: AppSettingsConnectionsRoute,
  AppSettingsMcpRoute: AppSettingsMcpRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsSecretsRoute: AppSettingsSecretsRoute,
  AppSettingsUsageRoute: AppSettingsUsageRoute,
  AppThreadsThreadIdRoute: AppThreadsThreadIdRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppBotsBotIdComputerRoute: AppBotsBotIdComputerRoute,
  AppBotsBotIdEditRoute: AppBotsBotIdEditRoute,
  AppBotsBotIdMemoryRoute: AppBotsBotIdMemoryRoute,
  AppBotsBotIdUsageRoute: AppBotsBotIdUsageRoute,
  AppThreadsThreadIdToolResultsRunIdCallIdRoute:
    AppThreadsThreadIdToolResultsRunIdCallIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
