// Generated by packages/adapters/scripts/record-pi-fixtures.mjs.
// Recorded from @earendil-works/pi-agent-core 0.85.1 with a scripted,
// offline stream function. Do not edit by hand: re-run the recorder on a pin
// change and review the diff against PI_EVENT_MAPPING.
import type { AgentEvent } from "@earendil-works/pi-agent-core";

export const abortedEvents: readonly AgentEvent[] = [
  {
    type: "agent_start",
  },
  {
    type: "turn_start",
  },
  {
    type: "message_start",
    message: {
      role: "user",
      content: [
        {
          type: "text",
          text: "work until stopped",
        },
      ],
      timestamp: 0,
    },
  },
  {
    type: "message_end",
    message: {
      role: "user",
      content: [
        {
          type: "text",
          text: "work until stopped",
        },
      ],
      timestamp: 0,
    },
  },
  {
    type: "message_start",
    message: {
      role: "assistant",
      content: [
        {
          type: "text",
          text: "working",
        },
      ],
      api: "openai-completions",
      provider: "openai",
      model: "corpus-model",
      usage: {
        input: 0,
        output: 0,
        cacheRead: 0,
        cacheWrite: 0,
        totalTokens: 0,
        cost: {
          input: 0,
          output: 0,
          cacheRead: 0,
          cacheWrite: 0,
          total: 0,
        },
      },
      stopReason: "pending",
      timestamp: 0,
    },
  },
  {
    type: "message_update",
    assistantMessageEvent: {
      type: "text_start",
      contentIndex: 0,
      partial: {
        role: "assistant",
        content: [
          {
            type: "text",
            text: "working",
          },
        ],
        api: "openai-completions",
        provider: "openai",
        model: "corpus-model",
        usage: {
          input: 0,
          output: 0,
          cacheRead: 0,
          cacheWrite: 0,
          totalTokens: 0,
          cost: {
            input: 0,
            output: 0,
            cacheRead: 0,
            cacheWrite: 0,
            total: 0,
          },
        },
        stopReason: "pending",
        timestamp: 0,
      },
    },
    message: {
      role: "assistant",
      content: [
        {
          type: "text",
          text: "working",
        },
      ],
      api: "openai-completions",
      provider: "openai",
      model: "corpus-model",
      usage: {
        input: 0,
        output: 0,
        cacheRead: 0,
        cacheWrite: 0,
        totalTokens: 0,
        cost: {
          input: 0,
          output: 0,
          cacheRead: 0,
          cacheWrite: 0,
          total: 0,
        },
      },
      stopReason: "pending",
      timestamp: 0,
    },
  },
  {
    type: "message_update",
    assistantMessageEvent: {
      type: "text_delta",
      contentIndex: 0,
      delta: "working",
      partial: {
        role: "assistant",
        content: [
          {
            type: "text",
            text: "working",
          },
        ],
        api: "openai-completions",
        provider: "openai",
        model: "corpus-model",
        usage: {
          input: 0,
          output: 0,
          cacheRead: 0,
          cacheWrite: 0,
          totalTokens: 0,
          cost: {
            input: 0,
            output: 0,
            cacheRead: 0,
            cacheWrite: 0,
            total: 0,
          },
        },
        stopReason: "pending",
        timestamp: 0,
      },
    },
    message: {
      role: "assistant",
      content: [
        {
          type: "text",
          text: "working",
        },
      ],
      api: "openai-completions",
      provider: "openai",
      model: "corpus-model",
      usage: {
        input: 0,
        output: 0,
        cacheRead: 0,
        cacheWrite: 0,
        totalTokens: 0,
        cost: {
          input: 0,
          output: 0,
          cacheRead: 0,
          cacheWrite: 0,
          total: 0,
        },
      },
      stopReason: "pending",
      timestamp: 0,
    },
  },
  {
    type: "message_end",
    message: {
      role: "assistant",
      content: [
        {
          type: "text",
          text: "working",
        },
      ],
      api: "openai-completions",
      provider: "openai",
      model: "corpus-model",
      usage: {
        input: 0,
        output: 0,
        cacheRead: 0,
        cacheWrite: 0,
        totalTokens: 0,
        cost: {
          input: 0,
          output: 0,
          cacheRead: 0,
          cacheWrite: 0,
          total: 0,
        },
      },
      stopReason: "aborted",
      timestamp: 0,
      errorMessage: "the operator stopped the run",
    },
  },
  {
    type: "turn_end",
    message: {
      role: "assistant",
      content: [
        {
          type: "text",
          text: "working",
        },
      ],
      api: "openai-completions",
      provider: "openai",
      model: "corpus-model",
      usage: {
        input: 0,
        output: 0,
        cacheRead: 0,
        cacheWrite: 0,
        totalTokens: 0,
        cost: {
          input: 0,
          output: 0,
          cacheRead: 0,
          cacheWrite: 0,
          total: 0,
        },
      },
      stopReason: "aborted",
      timestamp: 0,
      errorMessage: "the operator stopped the run",
    },
    toolResults: [],
  },
  {
    type: "agent_end",
    messages: [
      {
        role: "user",
        content: [
          {
            type: "text",
            text: "work until stopped",
          },
        ],
        timestamp: 0,
      },
      {
        role: "assistant",
        content: [
          {
            type: "text",
            text: "working",
          },
        ],
        api: "openai-completions",
        provider: "openai",
        model: "corpus-model",
        usage: {
          input: 0,
          output: 0,
          cacheRead: 0,
          cacheWrite: 0,
          totalTokens: 0,
          cost: {
            input: 0,
            output: 0,
            cacheRead: 0,
            cacheWrite: 0,
            total: 0,
          },
        },
        stopReason: "aborted",
        timestamp: 0,
        errorMessage: "the operator stopped the run",
      },
    ],
  },
];
