// Generated by packages/adapters/scripts/record-pi-fixtures.mjs.
// Recorded from @earendil-works/pi-agent-core 0.85.1 with a scripted,
// offline stream function. Do not edit by hand: re-run the recorder on a pin
// change and review the diff against PI_EVENT_MAPPING.
import type { AgentEvent } from "@earendil-works/pi-agent-core";

export const toolFailureEvents: readonly AgentEvent[] = [
  {
    type: "agent_start",
  },
  {
    type: "turn_start",
  },
  {
    type: "message_start",
    message: {
      role: "user",
      content: [
        {
          type: "text",
          text: "explode",
        },
      ],
      timestamp: 0,
    },
  },
  {
    type: "message_end",
    message: {
      role: "user",
      content: [
        {
          type: "text",
          text: "explode",
        },
      ],
      timestamp: 0,
    },
  },
  {
    type: "message_start",
    message: {
      role: "assistant",
      content: [
        {
          type: "toolCall",
          id: "call-explode-1",
          name: "explode",
          arguments: {},
        },
      ],
      api: "openai-completions",
      provider: "openai",
      model: "corpus-model",
      usage: {
        input: 0,
        output: 0,
        cacheRead: 0,
        cacheWrite: 0,
        totalTokens: 0,
        cost: {
          input: 0,
          output: 0,
          cacheRead: 0,
          cacheWrite: 0,
          total: 0,
        },
      },
      stopReason: "toolUse",
      timestamp: 0,
    },
  },
  {
    type: "message_update",
    assistantMessageEvent: {
      type: "toolcall_start",
      contentIndex: 0,
      partial: {
        role: "assistant",
        content: [
          {
            type: "toolCall",
            id: "call-explode-1",
            name: "explode",
            arguments: {},
          },
        ],
        api: "openai-completions",
        provider: "openai",
        model: "corpus-model",
        usage: {
          input: 0,
          output: 0,
          cacheRead: 0,
          cacheWrite: 0,
          totalTokens: 0,
          cost: {
            input: 0,
            output: 0,
            cacheRead: 0,
            cacheWrite: 0,
            total: 0,
          },
        },
        stopReason: "toolUse",
        timestamp: 0,
      },
    },
    message: {
      role: "assistant",
      content: [
        {
          type: "toolCall",
          id: "call-explode-1",
          name: "explode",
          arguments: {},
        },
      ],
      api: "openai-completions",
      provider: "openai",
      model: "corpus-model",
      usage: {
        input: 0,
        output: 0,
        cacheRead: 0,
        cacheWrite: 0,
        totalTokens: 0,
        cost: {
          input: 0,
          output: 0,
          cacheRead: 0,
          cacheWrite: 0,
          total: 0,
        },
      },
      stopReason: "toolUse",
      timestamp: 0,
    },
  },
  {
    type: "message_update",
    assistantMessageEvent: {
      type: "toolcall_delta",
      contentIndex: 0,
      delta: "{}",
      partial: {
        role: "assistant",
        content: [
          {
            type: "toolCall",
            id: "call-explode-1",
            name: "explode",
            arguments: {},
          },
        ],
        api: "openai-completions",
        provider: "openai",
        model: "corpus-model",
        usage: {
          input: 0,
          output: 0,
          cacheRead: 0,
          cacheWrite: 0,
          totalTokens: 0,
          cost: {
            input: 0,
            output: 0,
            cacheRead: 0,
            cacheWrite: 0,
            total: 0,
          },
        },
        stopReason: "toolUse",
        timestamp: 0,
      },
    },
    message: {
      role: "assistant",
      content: [
        {
          type: "toolCall",
          id: "call-explode-1",
          name: "explode",
          arguments: {},
        },
      ],
      api: "openai-completions",
      provider: "openai",
      model: "corpus-model",
      usage: {
        input: 0,
        output: 0,
        cacheRead: 0,
        cacheWrite: 0,
        totalTokens: 0,
        cost: {
          input: 0,
          output: 0,
          cacheRead: 0,
          cacheWrite: 0,
          total: 0,
        },
      },
      stopReason: "toolUse",
      timestamp: 0,
    },
  },
  {
    type: "message_update",
    assistantMessageEvent: {
      type: "toolcall_end",
      contentIndex: 0,
      toolCall: {
        type: "toolCall",
        id: "call-explode-1",
        name: "explode",
        arguments: {},
      },
      partial: {
        role: "assistant",
        content: [
          {
            type: "toolCall",
            id: "call-explode-1",
            name: "explode",
            arguments: {},
          },
        ],
        api: "openai-completions",
        provider: "openai",
        model: "corpus-model",
        usage: {
          input: 0,
          output: 0,
          cacheRead: 0,
          cacheWrite: 0,
          totalTokens: 0,
          cost: {
            input: 0,
            output: 0,
            cacheRead: 0,
            cacheWrite: 0,
            total: 0,
          },
        },
        stopReason: "toolUse",
        timestamp: 0,
      },
    },
    message: {
      role: "assistant",
      content: [
        {
          type: "toolCall",
          id: "call-explode-1",
          name: "explode",
          arguments: {},
        },
      ],
      api: "openai-completions",
      provider: "openai",
      model: "corpus-model",
      usage: {
        input: 0,
        output: 0,
        cacheRead: 0,
        cacheWrite: 0,
        totalTokens: 0,
        cost: {
          input: 0,
          output: 0,
          cacheRead: 0,
          cacheWrite: 0,
          total: 0,
        },
      },
      stopReason: "toolUse",
      timestamp: 0,
    },
  },
  {
    type: "message_end",
    message: {
      role: "assistant",
      content: [
        {
          type: "toolCall",
          id: "call-explode-1",
          name: "explode",
          arguments: {},
        },
      ],
      api: "openai-completions",
      provider: "openai",
      model: "corpus-model",
      usage: {
        input: 0,
        output: 0,
        cacheRead: 0,
        cacheWrite: 0,
        totalTokens: 0,
        cost: {
          input: 0,
          output: 0,
          cacheRead: 0,
          cacheWrite: 0,
          total: 0,
        },
      },
      stopReason: "toolUse",
      timestamp: 0,
    },
  },
  {
    type: "tool_execution_start",
    toolCallId: "call-explode-1",
    toolName: "explode",
    args: {},
  },
  {
    type: "tool_execution_end",
    toolCallId: "call-explode-1",
    toolName: "explode",
    result: {
      content: [
        {
          type: "text",
          text: "the corpus tool failed on purpose",
        },
      ],
      details: {},
    },
    isError: true,
  },
  {
    type: "message_start",
    message: {
      role: "toolResult",
      toolCallId: "call-explode-1",
      toolName: "explode",
      content: [
        {
          type: "text",
          text: "the corpus tool failed on purpose",
        },
      ],
      details: {},
      isError: true,
      timestamp: 0,
    },
  },
  {
    type: "message_end",
    message: {
      role: "toolResult",
      toolCallId: "call-explode-1",
      toolName: "explode",
      content: [
        {
          type: "text",
          text: "the corpus tool failed on purpose",
        },
      ],
      details: {},
      isError: true,
      timestamp: 0,
    },
  },
  {
    type: "turn_end",
    message: {
      role: "assistant",
      content: [
        {
          type: "toolCall",
          id: "call-explode-1",
          name: "explode",
          arguments: {},
        },
      ],
      api: "openai-completions",
      provider: "openai",
      model: "corpus-model",
      usage: {
        input: 0,
        output: 0,
        cacheRead: 0,
        cacheWrite: 0,
        totalTokens: 0,
        cost: {
          input: 0,
          output: 0,
          cacheRead: 0,
          cacheWrite: 0,
          total: 0,
        },
      },
      stopReason: "toolUse",
      timestamp: 0,
    },
    toolResults: [
      {
        role: "toolResult",
        toolCallId: "call-explode-1",
        toolName: "explode",
        content: [
          {
            type: "text",
            text: "the corpus tool failed on purpose",
          },
        ],
        details: {},
        isError: true,
        timestamp: 0,
      },
    ],
  },
  {
    type: "turn_start",
  },
  {
    type: "message_start",
    message: {
      role: "assistant",
      content: [
        {
          type: "text",
          text: "Recovered from the failure.",
        },
      ],
      api: "openai-completions",
      provider: "openai",
      model: "corpus-model",
      usage: {
        input: 0,
        output: 0,
        cacheRead: 0,
        cacheWrite: 0,
        totalTokens: 0,
        cost: {
          input: 0,
          output: 0,
          cacheRead: 0,
          cacheWrite: 0,
          total: 0,
        },
      },
      stopReason: "stop",
      timestamp: 0,
    },
  },
  {
    type: "message_update",
    assistantMessageEvent: {
      type: "text_start",
      contentIndex: 0,
      partial: {
        role: "assistant",
        content: [
          {
            type: "text",
            text: "Recovered from the failure.",
          },
        ],
        api: "openai-completions",
        provider: "openai",
        model: "corpus-model",
        usage: {
          input: 0,
          output: 0,
          cacheRead: 0,
          cacheWrite: 0,
          totalTokens: 0,
          cost: {
            input: 0,
            output: 0,
            cacheRead: 0,
            cacheWrite: 0,
            total: 0,
          },
        },
        stopReason: "stop",
        timestamp: 0,
      },
    },
    message: {
      role: "assistant",
      content: [
        {
          type: "text",
          text: "Recovered from the failure.",
        },
      ],
      api: "openai-completions",
      provider: "openai",
      model: "corpus-model",
      usage: {
        input: 0,
        output: 0,
        cacheRead: 0,
        cacheWrite: 0,
        totalTokens: 0,
        cost: {
          input: 0,
          output: 0,
          cacheRead: 0,
          cacheWrite: 0,
          total: 0,
        },
      },
      stopReason: "stop",
      timestamp: 0,
    },
  },
  {
    type: "message_update",
    assistantMessageEvent: {
      type: "text_delta",
      contentIndex: 0,
      delta: "Recovered from the failure.",
      partial: {
        role: "assistant",
        content: [
          {
            type: "text",
            text: "Recovered from the failure.",
          },
        ],
        api: "openai-completions",
        provider: "openai",
        model: "corpus-model",
        usage: {
          input: 0,
          output: 0,
          cacheRead: 0,
          cacheWrite: 0,
          totalTokens: 0,
          cost: {
            input: 0,
            output: 0,
            cacheRead: 0,
            cacheWrite: 0,
            total: 0,
          },
        },
        stopReason: "stop",
        timestamp: 0,
      },
    },
    message: {
      role: "assistant",
      content: [
        {
          type: "text",
          text: "Recovered from the failure.",
        },
      ],
      api: "openai-completions",
      provider: "openai",
      model: "corpus-model",
      usage: {
        input: 0,
        output: 0,
        cacheRead: 0,
        cacheWrite: 0,
        totalTokens: 0,
        cost: {
          input: 0,
          output: 0,
          cacheRead: 0,
          cacheWrite: 0,
          total: 0,
        },
      },
      stopReason: "stop",
      timestamp: 0,
    },
  },
  {
    type: "message_update",
    assistantMessageEvent: {
      type: "text_end",
      contentIndex: 0,
      content: "Recovered from the failure.",
      partial: {
        role: "assistant",
        content: [
          {
            type: "text",
            text: "Recovered from the failure.",
          },
        ],
        api: "openai-completions",
        provider: "openai",
        model: "corpus-model",
        usage: {
          input: 0,
          output: 0,
          cacheRead: 0,
          cacheWrite: 0,
          totalTokens: 0,
          cost: {
            input: 0,
            output: 0,
            cacheRead: 0,
            cacheWrite: 0,
            total: 0,
          },
        },
        stopReason: "stop",
        timestamp: 0,
      },
    },
    message: {
      role: "assistant",
      content: [
        {
          type: "text",
          text: "Recovered from the failure.",
        },
      ],
      api: "openai-completions",
      provider: "openai",
      model: "corpus-model",
      usage: {
        input: 0,
        output: 0,
        cacheRead: 0,
        cacheWrite: 0,
        totalTokens: 0,
        cost: {
          input: 0,
          output: 0,
          cacheRead: 0,
          cacheWrite: 0,
          total: 0,
        },
      },
      stopReason: "stop",
      timestamp: 0,
    },
  },
  {
    type: "message_end",
    message: {
      role: "assistant",
      content: [
        {
          type: "text",
          text: "Recovered from the failure.",
        },
      ],
      api: "openai-completions",
      provider: "openai",
      model: "corpus-model",
      usage: {
        input: 0,
        output: 0,
        cacheRead: 0,
        cacheWrite: 0,
        totalTokens: 0,
        cost: {
          input: 0,
          output: 0,
          cacheRead: 0,
          cacheWrite: 0,
          total: 0,
        },
      },
      stopReason: "stop",
      timestamp: 0,
    },
  },
  {
    type: "turn_end",
    message: {
      role: "assistant",
      content: [
        {
          type: "text",
          text: "Recovered from the failure.",
        },
      ],
      api: "openai-completions",
      provider: "openai",
      model: "corpus-model",
      usage: {
        input: 0,
        output: 0,
        cacheRead: 0,
        cacheWrite: 0,
        totalTokens: 0,
        cost: {
          input: 0,
          output: 0,
          cacheRead: 0,
          cacheWrite: 0,
          total: 0,
        },
      },
      stopReason: "stop",
      timestamp: 0,
    },
    toolResults: [],
  },
  {
    type: "agent_end",
    messages: [
      {
        role: "user",
        content: [
          {
            type: "text",
            text: "explode",
          },
        ],
        timestamp: 0,
      },
      {
        role: "assistant",
        content: [
          {
            type: "toolCall",
            id: "call-explode-1",
            name: "explode",
            arguments: {},
          },
        ],
        api: "openai-completions",
        provider: "openai",
        model: "corpus-model",
        usage: {
          input: 0,
          output: 0,
          cacheRead: 0,
          cacheWrite: 0,
          totalTokens: 0,
          cost: {
            input: 0,
            output: 0,
            cacheRead: 0,
            cacheWrite: 0,
            total: 0,
          },
        },
        stopReason: "toolUse",
        timestamp: 0,
      },
      {
        role: "toolResult",
        toolCallId: "call-explode-1",
        toolName: "explode",
        content: [
          {
            type: "text",
            text: "the corpus tool failed on purpose",
          },
        ],
        details: {},
        isError: true,
        timestamp: 0,
      },
      {
        role: "assistant",
        content: [
          {
            type: "text",
            text: "Recovered from the failure.",
          },
        ],
        api: "openai-completions",
        provider: "openai",
        model: "corpus-model",
        usage: {
          input: 0,
          output: 0,
          cacheRead: 0,
          cacheWrite: 0,
          totalTokens: 0,
          cost: {
            input: 0,
            output: 0,
            cacheRead: 0,
            cacheWrite: 0,
            total: 0,
          },
        },
        stopReason: "stop",
        timestamp: 0,
      },
    ],
  },
];
