import { sql } from "drizzle-orm";
import { uuid } from "drizzle-orm/pg-core";

/**
 * The primary-key convention every table in this schema follows: a UUIDv7,
 * generated by Postgres 18's built-in `uuidv7()`.
 *
 * UUIDv7 is time-ordered, so an id sorts by creation order and an index on it
 * stays close to insertion order instead of scattering like UUIDv4. That is the
 * whole reason the PRD chose Postgres 18 over 17 (PRD stack decision 16), and a
 * table that hand-rolls its id loses the property. The schema suite fails when a
 * table's primary key is not this column, so the convention is checked rather
 * than merely stated.
 */
export function primaryKeyId() {
  return uuid("id")
    .primaryKey()
    .default(sql`uuidv7()`);
}
